# Generated by Django 4.2.3 on 2023-07-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='FollowersCount',
        ),
    ]
